version: '3.8'

services:
  backend:
    build: ./backend
    command: python /usr/backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/usr/backend
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  frontend:
    container_name: answer-frontend
    build: ./frontend
    working_dir: /usr/frontend/testapp
    tty: true
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/usr/frontend
    ports:
      - "3000:3000"

volumes:
  postgres_data: