version: "3.9"
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/backend-server
    ports:
      - "8000:8000"
    tty: true
    working_dir: "/backend-server"
